package(default_visibility = ["//visibility:public"])

load("@angular//:index.bzl", "ng_module")

ng_module(
    name = "my-footer",
    srcs = glob(["*.ts"]),
    tsconfig = "//src:tsconfig.json",
    deps = ["@rxjs"],
)
